Researchportal/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
# import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('projects/', include('posts.urls')),
    path('users/', include('usr_val.urls')),


    path('reset_password/',
    auth_views.PasswordResetView.as_view(template_name="usr_val/password_reset.html"),
    name="reset_password"),

    path('reset_password_sent/', 
    auth_views.PasswordResetDoneView.as_view(template_name="usr_val/password_reset_sent.html"), 
    name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
    auth_views.PasswordResetConfirmView.as_view(template_name="usr_val/password_reset_form.html"), 
    name="password_reset_confirm"),

    path('reset_password_complete/', 
    auth_views.PasswordResetCompleteView.as_view(template_name="usr_val/password_reset_done.html"), 
    name="password_reset_complete"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path, include
from . import views


app_name = 'home'

urlpatterns = [
    path('', views.home , name= 'home'),
    path('about/', views.about , name= 'about'),
    path('director/', views.director , name= 'director'),
    path('mile/', views.mile , name= 'mile'),
    path('team/', views.team , name= 'team'),
]

posts/urls.py
from django.urls import path, include
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.feed, name = 'feed'),
    
]

usr_val/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'usr_val'

urlpatterns = [
    
    # Auth
    path('signupuser/', views.SignupUser.as_view() , name="signupuser"),
    path('signupstudent/', views.SignupStudent.as_view() , name="signupstudent"),

    path('loginuser/', views.LoginUser.as_view() , name="loginuser"),
    path('logout/', views.logoutuser, name='logoutuser'),
    

    # Teacher

    path('teacher/',views.TeacherCreateView.as_view() , name='teacher'),
    path('student/',views.StudentCreateView.as_view() , name='student'),


    # post creation 
    path('teacherd/', views.TeacherPostCreation.as_view(), name='teacherd'),
    path('student', views.studentd, name='studentd'),

    # individual posts
    path('project/<int:post_id>/', views.apply, name='apply'),

    #info
    path('info', views.info , name= 'info' ),
    path('stinfo/<int:sid>', views.stinfo , name= 'stinfo' ),


    # email reset 

]

templates/partials/_footer.html
<!-- Footer -->

<footer class="text-center text-lg-start bg-dark text-light">
    <!-- Section: Social media -->
    <section
      class="d-flex 
      container justify-content-center justify-content-lg-between p-4 border-bottom"
    >
      <!-- Left -->
      <div class="me-5 d-none d-lg-block">
        <span>Get connected with us on social networks:</span>
      </div>
      <!-- Left -->
  
      <!-- Right -->
      <div>
        <a href="" class="me-4 text-reset text-decoration-none">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="" class="me-4 text-reset text-decoration-none">
          <i class="fab fa-google"></i>
        </a>
        <a href="" class="me-4 text-reset text-decoration-none">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="" class="me-4 text-reset text-decoration-none">
          <i class="fab fa-linkedin"></i>
        </a>
        <a href="" class="me-4 text-reset text-decoration-none">
          <i class="fab fa-github"></i>
        </a>
      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->
  
    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold mb-4">
              IEEE SB NITDgp
            </h6>
            <p>
                The IEEE Student Branch , NIT Durgapur is a society of enthusiasts aimed at promoting research-related activities in the campus.
                 We are a direct handshake to IEEE, an international body that allows countless young researchers the opportunity to present 
                 & publish their innovations every year. Comprising of bright researchers, developers, speakers,
                and other contributors we are a society that welcomes in the era of better research prospects, on the campus.
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Check Out our other links
            </h6>
            <p>
              <a href="#!" class="text-reset text-decoration-none">Angular</a>
            </p>
            <p>
              <a href="#!" class="text-reset text-decoration-none">React</a>
            </p>
            <p>
              <a href="#!" class="text-reset text-decoration-none">Vue</a>
            </p>
            <p>
              <a href="#!" class="text-reset text-decoration-none">Laravel</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Useful links
            </h6>
            <p>
              <a href="#!" class="text-reset text-decoration-none">Pricing</a>
            </p>
            <p>
              <a href="#!" class="text-reset text-decoration-none">Settings</a>
            </p>
            <p>
              <a href="#!" class="text-reset text-decoration-none">Orders</a>
            </p>
            <p>
              <a href="#!" class="text-reset text-decoration-none">Help</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Contact
            </h6>
            <p><i class="fas fa-home me-3"></i>NIT Durgapur
                Mahatma Gandhi Avenue, Durgapur, West Bengal,India</p>
            <p>
              <i class="fas fa-envelope me-3"></i>
              ieeesb.nitdgp@gmail.com
            </p>
            <p><i class="fas fa-phone me-3"></i> 
                +919476211060</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->
  
    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
      © 2021 Copyright:
      <a class="text-reset fw-bold text-decoration-none" href="https://www.ieeesbnitdgp.com/" target="_blank">IEEE SB NITDgp</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

templates/partials/_navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <img src="{% static 'img/portal_logo_big3.png' %}" alt="" width="120" height="24">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}" >Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'posts:feed' %}" >Projects Feed</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'home:about' %}" >About Us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'home:team' %}" >Team</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'home:mile' %}" >Milestones Reached</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'home:director' %}" >Director's Message</a>
          </li>
            
          {% if user.is_authenticated %}

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dashboard
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              
              {%  ifequal 'teacher' grp  %}
              <li><a class="dropdown-item" href="{% url 'usr_val:teacher' %}" >Update Info</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'usr_val:teacherd' %}">Dashboard</a></li>
              <li><a class="dropdown-item" href="{% url 'usr_val:info' %}">Projects Info</a></li>
              {% endifequal %}

              {%  ifequal 'student' grp  %}
              <li><a class="dropdown-item" href="{% url 'usr_val:student' %}" >Update Info</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'usr_val:studentd' %}">Dashboard</a></li>
              {% endifequal %}
              
            </ul>
          </li>

          <li class="nav-item">
            <a href="#" onclick="$('#signOutBtn').click()" class="nav-link">Logout</a>
            <form style='display: none;' method="POST" action="{% url 'usr_val:logoutuser' %}">
              {% csrf_token %}
              <button id="signOutBtn" type="submit">Logout</button>
            </form>
          </li>

          {% else %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Signup/Login
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'usr_val:signupuser' %}" >Signup as Faculty</a></li>
              <li><a class="dropdown-item" href="{% url 'usr_val:signupstudent' %}" >Signup as Student</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'usr_val:loginuser'%}">Login</a></li>
            </ul>
          </li>
          


          {% endif %}
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
  