Researchportal/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
# import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('projects/', include('posts.urls')),
    path('users/', include('usr_val.urls')),


    path('reset_password/',
    auth_views.PasswordResetView.as_view(template_name="usr_val/password_reset.html"),
    name="reset_password"),

    path('reset_password_sent/', 
    auth_views.PasswordResetDoneView.as_view(template_name="usr_val/password_reset_sent.html"), 
    name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
    auth_views.PasswordResetConfirmView.as_view(template_name="usr_val/password_reset_form.html"), 
    name="password_reset_confirm"),

    path('reset_password_complete/', 
    auth_views.PasswordResetCompleteView.as_view(template_name="usr_val/password_reset_done.html"), 
    name="password_reset_complete"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path, include
from . import views


app_name = 'home'

urlpatterns = [
    path('', views.home , name= 'home'),
    path('about/', views.about , name= 'about'),
    path('director/', views.director , name= 'director'),
    path('mile/', views.mile , name= 'mile'),
    path('team/', views.team , name= 'team'),
]

usr_val/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'usr_val'

urlpatterns = [
    
    # Auth
    path('signupuser/', views.SignupUser.as_view() , name="signupuser"),
    path('signupstudent/', views.SignupStudent.as_view() , name="signupstudent"),

    path('loginuser/', views.LoginUser.as_view() , name="loginuser"),
    path('logout/', views.logoutuser, name='logoutuser'),
    

    # Teacher

    path('teacher/',views.TeacherCreateView.as_view() , name='teacher'),
    path('student/',views.StudentCreateView.as_view() , name='student'),


    # post creation 
    path('teacherd/', views.TeacherPostCreation.as_view(), name='teacherd'),
    path('student', views.studentd, name='studentd'),

    # individual posts
    path('project/<int:post_id>/', views.apply, name='apply'),

    #info
    path('info', views.info , name= 'info' ),
    path('stinfo/<int:sid>', views.stinfo , name= 'stinfo' ),


    # email reset 

]

usr_val/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Teacher(models.Model):

    branch = models.CharField(blank=True, max_length=200)
    contact = models.CharField(blank=True,max_length=200)
    user = models.OneToOneField(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.user.username

#student
class Student(models.Model):

    branch = models.CharField(blank=True, max_length=200)
    contact = models.CharField(blank=True,max_length=200)
    user = models.OneToOneField(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.user.username

usr_val/forms.py
from django.db.models import fields
from django.forms import ModelForm

from posts import models
import posts
from .models import Teacher
from django.contrib.auth.models import User
from django import forms
from posts.models import Post

class TeacherDetails(forms.Form):
    first_name = forms.CharField(max_length=400, label="Enter Your First Name") 
    last_name = forms.CharField(max_length=400, label="Enter Your Last Name")
    email = forms.EmailField(label='Please Enter Your Work Email')
    branch = forms.CharField(max_length=400, label="Enter Your college department")
    contact = forms.CharField(min_length=10, max_length=10, label="Enter your Phone Number", required=False)

class StudentDetails(forms.Form):
    first_name = forms.CharField(max_length=400, label="Enter Your First Name") 
    last_name = forms.CharField(max_length=400, label="Enter Your Last Name")
    email = forms.EmailField(label='Please Enter Your Work Email')
    branch = forms.CharField(max_length=400, label="Enter Your college department")
    contact = forms.CharField(min_length=10, max_length=10, label="Enter your Phone Number", required=False)

class PostCreationForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title','image_url','tag','description']
        

usr_val/views.py
from django.http.response import HttpResponseNotAllowed
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import render
from django.views import View 
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .models import Teacher,Student
from django.views.generic.edit import FormView, UpdateView, FormMixin
from django.contrib.auth.models import Group
from django.contrib import messages
from .forms import PostCreationForm, TeacherDetails, StudentDetails
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from posts.models import Post
from django.core.mail import send_mail


# teacher 

# Create your views here.
class SignupUser(View) :

    def get(self, request):
        return render(request, 'usr_val/signupuser.html', {'form':UserCreationForm()})


    def post(self,request):
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                user.save()
                group = Group.objects.get(name='teacher')
                user.groups.add(group)
                t = Teacher.objects.create(
                user=user)
                t.save()
                messages.success(request, 'Account was created for ' + user.username)           
                
                login(request, user)
                return redirect('home:home')
            except IntegrityError:
                return render(request, 'usr_val/signupuser.html', {'form':UserCreationForm(), 'error':'That username has already been taken. Please choose a new username'})
        else:
            return render(request, 'usr_val/signupuser.html', {'form':UserCreationForm(), 'error':'Passwords did not match'})


class LoginUser(View):

    def get(self,request):
        return render(request, 'usr_val/loginuser.html', {'form':AuthenticationForm()})

    def post(self,request):
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'usr_val/loginuser.html', {'form':AuthenticationForm(), 'error':'Username and password did not match'})
        else:
            login(request, user)
            return redirect('home:home')


@login_required
def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home:home')





class TeacherCreateView(LoginRequiredMixin,  FormView):
    template_name = 'usr_val/tdashboard.html'
    form_class = TeacherDetails
    success_url = '/'

    def form_valid(self, form):
        my_form = form.cleaned_data
        model = get_object_or_404(Teacher, user = self.request.user)
        model.user.first_name = my_form['first_name']
        model.user.last_name = my_form['last_name']
        model.user.email = my_form['email']
        model.user.save()

        model.branch = my_form['branch']
        model.contact = my_form['contact']
        model.save()

        with open('text_messages/login_user.txt', 'r') as file:
            data_email = file.read()

        send_mail(
                'Signup Sucessfull',
                str(data_email).format(model.user.first_name , model.user.first_name , 
                model.user.last_name, model.contact , model.user.username ),
                'ieeesbnitd@gmail.com',
                [model.user.email],
                fail_silently=False,
                )
        
        return super().form_valid(form)




# student
class SignupStudent(View) :

    def get(self, request):
        return render(request, 'usr_val/signupstudent.html', {'form':UserCreationForm()})


    def post(self,request):
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                user.save()
                group = Group.objects.get(name='student')
                user.groups.add(group)
                t = Student.objects.create(
                user=user)
                t.save()
                messages.success(request, 'Account was created for ' + user.username)                
                
                login(request, user)
                return redirect('home:home')
            except IntegrityError:
                return render(request, 'usr_val/signupuser.html', {'form':UserCreationForm(), 'error':'That username has already been taken. Please choose a new username'})
        else:
            return render(request, 'usr_val/signupstudent.html', {'form':UserCreationForm(), 'error':'Passwords did not match'})



class StudentCreateView(LoginRequiredMixin,  FormView):
    template_name = 'usr_val/sdashboard.html'
    form_class = StudentDetails
    success_url = '/'

    def form_valid(self, form):
        my_form = form.cleaned_data
        model = get_object_or_404(Student, user = self.request.user)
        model.user.first_name = my_form['first_name']
        model.user.last_name = my_form['last_name']
        model.user.email = my_form['email']
        model.user.save()

        model.branch = my_form['branch']
        model.contact = my_form['contact']
        model.save()

        with open('text_messages/login_user.txt', 'r') as file:
            data_email = file.read()

        send_mail(
                'Signup Sucessfull',
                str(data_email).format(model.user.first_name , model.user.first_name , 
                model.user.last_name, model.contact , model.user.username ),
                'ieeesbnitd@gmail.com',
                [model.user.email],
                fail_silently=True,
                )
        
        return super().form_valid(form)






class TeacherPostCreation(LoginRequiredMixin, CreateView ):
    # model = Post
    form_class = PostCreationForm
    template_name = 'usr_val/teacherd.html'
    success_url = '/projects/'


    def form_valid(self,form):
        obj = form.save(commit = False)
        # print(obj)
        acessor = get_object_or_404(Teacher, user = self.request.user)
        obj.teacher = acessor
        obj.save()
        return super().form_valid(form)

        


def studentd(request):
    return render(request, 'usr_val/studentd.html')


@login_required
def apply(request, post_id):

    

    project = get_object_or_404(Post, pk = post_id)
    try :
        student = get_object_or_404(Student, user = request.user)
    except :
        student = None
    
    st_apply = False

    if request.method == 'GET':
        if student in project.student.all() :
            st_apply = True
        
        return render(request, 'usr_val/apply.html', {'i' : project , 'apply' :st_apply })


    if request.method == 'POST':

        if student == None :
            return HttpResponse("Only students can apply to a project")
        
        else : 

            message = 'please try later'

            if student not in project.student.all() :
                project.student.add(student)
                
                project.save()
                message = "You have Sucessfully Apllied to this project"

            else :
                message = "You have already apllied to this project"

            return render(request, 'usr_val/apply.html' , {'message' : message , 'i' : project})


    

@login_required
def info(request) :
    user = request.user
    teacher = get_object_or_404(Teacher, user = user)
    posts = Post.objects.filter(teacher = teacher)
    # print(posts.get(title = 'Matlab Mastery').student.all())
    # print(posts.student)
    return render(request, 'usr_val/info.html', {'posts' : posts})

@login_required
def stinfo(request, sid) :
    teacher = get_object_or_404(Teacher, user = request.user)
    project = get_object_or_404(Post, pk = sid)
    students = project.student.all()
    return render(request, 'usr_val/stinfo.html', {'students':students , 'project':project})

templates/usr_val/apply.html
<!DOCTYPE html>
{% extends 'base.html' %} {% load static %} {% block content %}
<head>
    <title>{% block title%} {{i.title}} {% endblock %}</title>
</head>

<div class="container">
    <div class="card" style="width: 36rem;" >
        <img src="{{i.image_url}}" class="card-img-top" alt="...">
        <div class="card-body">
        <h5 class="card-title">{{i.title }}</h5>
        <p class="card-text">{{i.description}}</p>
        <p class="card-text fw-bold">
            {{i.tag}}
        </p>
        
        <h4>
            Posted By
        </h4>
        <p>
            {{i.teacher.user.username}}
        </p>


        <a href="{% url 'usr_val:apply' i.id %}" class="btn btn-primary">Know More</a>
        </div>

        <hr>
        
    </div>

    <br>

    <div class="container">
        {% if apply %}
        <div class="alert alert-success" role="alert">
            You have already applied to this project
          </div>

        
        {% else %}

        <form method = "POST" class="form-group" >
            {% csrf_token %}

            <p>
                To apply to this project click the button below
            </p>

            <button type="submit" class="btn btn-success"> Apply </button>
        </form>

        {% endif %}

        <div class="alert alert-success" role="alert">
            {{message}}
        </div>
        



    </div>
</div>


{% endblock %}

templates/usr_val/index.html
<!DOCTYPE html>
{% extends 'base.html' %} {% load static %} {% block content %}
{% endblock %}

templates/usr_val/info.html
<!DOCTYPE html>
{% extends 'base.html' %} {% load static %} {% block content %}
<head>
    <title>{% block title%} Information {% endblock %}</title>
</head>

<div class="container">
    <table class="table table-dark">
        <thead>
          <tr>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
          </tr>
        </thead>
        {% for i in posts %}
        <tbody>
          <tr>
            <td> <a href="{% url 'usr_val:stinfo' i.id %}">{{i.title }} </a></td>
            <td> 

                {{i.description}}
            </td>
          </tr>
        </tbody>

        {% endfor %}
      </table>
</div>


{% endblock %}

templates/usr_val/loginuser.html
{% extends "base.html" %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Login</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" class="form-control" id="username">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password" class="form-control" id="password">
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
            <hr>
            <br>
            <div class="text-center">
                Need an account? <a href="{% url 'usr_val:signupuser' %}">Sign Up here</a>
            </div>

            <div class="d-flex justify-content-center links">
                Forgot password? <a href="{% url 'reset_password' %}" class="ml-2">Reset password</a>
            </div>
            <br>
        </div>
    </div>
{% endblock %}

templates/usr_val/password_reset.html
{% extends "base.html" %}

{% block content %}
<div class="container">

		
	<h3>Password reset</h3>

	<p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>

	<form method="post" class="form-group">

		{% csrf_token %}
		{{form.as_p}}
		<input type="Submit" name="Send email" class="form-control" class="btn btn-primary">
		
	</form>

</div>


{% endblock %}

templates/usr_val/password_reset_done.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <h3>Password reset complete</h3>

    <p>Your password has been set. You may go ahead and log in now.</p>

    <a href="/">Log in</a>
    
</div>
{% endblock %}

templates/usr_val/password_reset_sent.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    
    <h3>Password reset sent</h3>


    <p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

    <p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>

</div>

{% endblock %}

templates/usr_val/sdashboard.html
{% extends 'base.html' %}

{% block content %}

<h3>
    Student Dashboard
</h3>

<div class="container">
    <form method="POST" class="form-group">
        {% csrf_token %}
        {{form.as_p}}

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

templates/usr_val/signupstudent.html
<!DOCTYPE html>
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        <h2>Sign Up As Student</h2>
    </div>
</div>
<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        {% if error %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" name="username" class="form-control" id="username" aria-describedby="usernameHelp">
                <small id="usernameHelp" class="form-text text-muted">Your username must be unique. We'll let you know if someone has taken it already.</small>
            </div>
            <div class="form-group">
                <label for="password1">Password</label>
                <input type="password" name="password1" class="form-control" id="password1">
            </div>
            <div class="form-group">
                <label for="password2">Confirm Password</label>
                <input type="password" name="password2" class="form-control" id="password2">
            </div>
            <button type="submit" class="btn btn-primary">Sign Up</button>
        </form>

        <p>
            {{form.errors}}
        </p>

        <hr>
        <div class="text-center">
            Do you already have an account? <a href="{% url 'usr_val:loginuser' %}">Login here</a>
        </div>
    </div>
</div>


{% endblock %}

templates/usr_val/signupuser.html
<!DOCTYPE html>
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        <h2>Sign Up As Faculty</h2>
    </div>
</div>
<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        {% if error %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" name="username" class="form-control" id="username" aria-describedby="usernameHelp">
                <small id="usernameHelp" class="form-text text-muted">Your username must be unique. We'll let you know if someone has taken it already.</small>
            </div>
            <div class="form-group">
                <label for="password1">Password</label>
                <input type="password" name="password1" class="form-control" id="password1">
            </div>
            <div class="form-group">
                <label for="password2">Confirm Password</label>
                <input type="password" name="password2" class="form-control" id="password2">
            </div>
            <button type="submit" class="btn btn-primary">Sign Up</button>
        </form>

        <p>
            {{form.errors}}
        </p>

        <hr>
        <div class="text-center">
            Do you already have an account? <a href="{% url 'usr_val:loginuser' %}">Login here</a>
        </div>
    </div>
</div>


{% endblock %}

templates/usr_val/stinfo.html
<!DOCTYPE html>
{% extends 'base.html' %} {% load static %} {% block content %}
<head>
    <title>{% block title%} Information {% endblock %}</title>
</head>

<div class="container">

  <h2>
    {{project.title}}
  </h2>

    <table class="table table-dark">
        <thead>
          <tr>
            <th scope="col">Student Name</th>
            <th scope="col">Branch</th>
            <th scope="col">Email</th>

          </tr>
        </thead>
        {% for i in students %}
        <tbody>
          <tr>
            <td> {{i.user.first_name }}  {{ i.user.last_name}} </td>
            <td> 

                {{i.branch}}
            </td>
            <td>
              {{i.user.email}}
            </td>
          </tr>
        </tbody>

        {% endfor %}
      </table>
</div>


{% endblock %}

templates/usr_val/studentd.html
<!DOCTYPE html>
{% extends 'base.html' %} {% load static %} {% block content %}
<head>
    <title>{% block title%} Student Dashboard{% endblock %}</title>
</head>

<div class="container">
    Hello {{ user.username }}, !!!

    <div class="container">
        <h4>
            Personal Details
        </h4>

        <p>
            <ol>
                <li>
                    {{user.first_name}}
                </li>
                <li>
                    {{user.last_name}}
                </li>
                <li>
                    {{user.email}}
                </li>
            </ol>
        </p>
    </div>
  
{% endblock %}

templates/usr_val/tdashboard.html
{% extends 'base.html' %}

{% block content %}

<h3>
    Teacher Dashboard
</h3>

<div class="container">
    <form method="POST" class="form-group">
        {% csrf_token %}
        {{form.as_p}}

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

templates/usr_val/teacherd.html
<!DOCTYPE html>
{% extends 'base.html' %} {% load static %} {% block content %}
<head>
    <title>{% block title%} Dashboard {% endblock %}</title>
</head>

    <div class="container">
        Hello sir, {{ user.username }} !!!

        <div class="container">
            <h4>
                Personal Details
            </h4>

            <p>
                <ol>
                    <li>
                        {{user.first_name}}
                    </li>
                    <li>
                        {{user.last_name}}
                    </li>
                    <li>
                        {{user.email}}
                    </li>
                </ol>
            </p>
        </div>

        <hr>

        <h3>
            Create a Project
        </h3>
        

        <div class="container">


            <form class="form-group" method="POST">
                {% csrf_token %}
                {{form.as_p}}
    
                <input type="submit" value="save"/>
        
            </form>

        </div>
        
    </div>
  
{% endblock %}